
-- ═══ RESET: Drop all existing tables, functions, types ═══
DROP TABLE IF EXISTS production_entries CASCADE;
DROP TABLE IF EXISTS packaging_entries CASCADE;
DROP TABLE IF EXISTS lots CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS clothing_types CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;

DROP FUNCTION IF EXISTS has_role CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;

DROP TYPE IF EXISTS lot_status CASCADE;
DROP TYPE IF EXISTS app_role CASCADE;

-- ═══ New enums ═══
CREATE TYPE app_role AS ENUM ('admin', 'cliente', 'motorista', 'producao');
CREATE TYPE order_status AS ENUM ('cadastrado', 'aguardando_coleta', 'coletado', 'em_lavagem', 'finalizado', 'entregue');
CREATE TYPE charge_type AS ENUM ('por_peca', 'por_peso');

-- ═══ Tables ═══
CREATE TABLE profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text,
  address text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL,
  UNIQUE(user_id, role)
);

CREATE TABLE clothing_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  unit text NOT NULL DEFAULT 'PEÇA',
  active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number int GENERATED BY DEFAULT AS IDENTITY,
  client_id uuid NOT NULL REFERENCES profiles(id),
  status order_status NOT NULL DEFAULT 'cadastrado',
  charge_type charge_type NOT NULL DEFAULT 'por_peca',
  weight_kg numeric,
  client_notes text,
  collection_notes text,
  production_notes text,
  driver_id uuid REFERENCES profiles(id),
  collected_at timestamptz,
  has_divergence boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  clothing_type_id uuid NOT NULL REFERENCES clothing_types(id),
  quantity_registered int NOT NULL DEFAULT 0,
  quantity_checked int,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ═══ Functions ═══
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE OR REPLACE FUNCTION public.create_user_profile(_name text, _role app_role DEFAULT 'cliente')
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF _role != 'cliente' AND NOT has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Apenas admins podem atribuir perfis não-cliente';
  END IF;
  INSERT INTO profiles (id, name) VALUES (auth.uid(), _name) ON CONFLICT (id) DO NOTHING;
  INSERT INTO user_roles (user_id, role) VALUES (auth.uid(), _role) ON CONFLICT (user_id, role) DO NOTHING;
END;
$$;

-- ═══ Triggers ═══
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ═══ RLS ═══
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clothing_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Profiles
CREATE POLICY "Authenticated view profiles" ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users insert own profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins update any profile" ON profiles FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- User roles
CREATE POLICY "View own roles" ON user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins view all roles" ON user_roles FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins insert roles" ON user_roles FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins update roles" ON user_roles FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins delete roles" ON user_roles FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Clothing types
CREATE POLICY "View clothing types" ON clothing_types FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admin insert clothing types" ON clothing_types FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admin update clothing types" ON clothing_types FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admin delete clothing types" ON clothing_types FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Orders
CREATE POLICY "Client view own orders" ON orders FOR SELECT TO authenticated USING (client_id = auth.uid());
CREATE POLICY "Admin view all orders" ON orders FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Driver view assigned orders" ON orders FOR SELECT TO authenticated USING (driver_id = auth.uid());
CREATE POLICY "Production view orders" ON orders FOR SELECT TO authenticated USING (has_role(auth.uid(), 'producao'));
CREATE POLICY "Client create orders" ON orders FOR INSERT TO authenticated WITH CHECK (client_id = auth.uid());
CREATE POLICY "Admin create orders" ON orders FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admin update orders" ON orders FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Driver update assigned" ON orders FOR UPDATE TO authenticated USING (driver_id = auth.uid());
CREATE POLICY "Production update orders" ON orders FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'producao'));
CREATE POLICY "Admin delete orders" ON orders FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- Order items
CREATE POLICY "View accessible items" ON order_items FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND (
    orders.client_id = auth.uid() OR orders.driver_id = auth.uid() OR
    has_role(auth.uid(), 'admin') OR has_role(auth.uid(), 'producao')))
);
CREATE POLICY "Client insert items" ON order_items FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.client_id = auth.uid())
);
CREATE POLICY "Admin insert items" ON order_items FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Production update items" ON order_items FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id) AND has_role(auth.uid(), 'producao')
);
CREATE POLICY "Admin update items" ON order_items FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admin delete items" ON order_items FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));
